spring:
  application:
    name: gh-admin
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 550000
  web:
    resources:
      static-locations: classpath:/static/

server:
  port: 8081

mybatis-plus:
  mapper-locations: classpath*:./mappers/**/*.xml

aws:
  sqs:
    base-queue-url: ${AWS_SQS_BASE_QUEUE_URL}
    region: ${AWS_REGION}
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}

cloudflare:
  aws:
    s3:
      endpoint: ${CLOUDFLARE_S3_ENDPOINT}
      bucket-name: ${CLOUDFLARE_BUCKET_NAME}
      cdn-domain: ${CLOUDFLARE_CDN_DOMAIN}
      region: auto
      credentials:
        access-key: ${CLOUDFLARE_ACCESS_KEY}
        secret-key: ${CLOUDFLARE_SECRET_KEY}