spring:
  application:
    name: gh-gif
  # 启用虚拟线程支持
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  datasource:
    url: jdbc:mysql://localhost:3306/gif_hub?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  boot:
    admin:
      client:
        url: http://localhost:8081

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:./mappers/**/*.xml
server:
  port: 8080

# actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'

# AWS SQS 配置
aws:
  sqs:
    # 基础队列URL
    base-queue-url:
    # 邮件队列URL
    email-queue-url:
    # AWS区域
    region:
  # AWS凭据
  access-key-id:
  secret-access-key:

# cloudflare r2
cloudflare:
  aws:
    s3:
      # 替换为实际accountID
      endpoint:
      # 替换为实际存储桶名
      bucket-name: gif-hub
      # 替换为自定义域名
      cdn-domain: mynnmy.top
      # 自动识别区域
      region: auto
      credentials:
        # 替换为API访问密钥
        access-key:
        # 替换为API秘密密钥
        secret-key:

