# gh-weixin/railway.toml
[build]
builder = "nixpacks"
buildCommand = "mvn -B -DskipTests clean install && ls -la gh-weixin/target/ && mkdir -p target && cp gh-weixin/target/*.jar target/ && ls -la target/"

[deploy]
startCommand = "java -jar target/gh-weixin-0.0.1-SNAPSHOT.jar"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10