# gh-gif/railway.toml
[build]
builder = "nixpacks"
buildCommand = "mvn -B -DskipTests clean install && ls -la gh-gif/target/ && mkdir -p target && cp gh-gif/target/*.jar target/ && ls -la target/"

[deploy]
startCommand = "java -jar target/gh-gif-0.0.1-SNAPSHOT.jar"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10