[deploy]
# 明确指定启动 gh-gif 的 jar 包（多模块项目必须指定具体文件名）
startCommand = "java -Dserver.port=$PORT $JAVA_OPTS -jar target/gh-gif-0.0.1-SNAPSHOT.jar"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
