spring:
  application:
    name: gh-weixin
  data:
    redis:
      url: ${REDIS_URL}
#      host: ${REDIS_HOST}
#      port: ${REDIS_PORT}
#      username: ${REDIS_USERNAME:default}
#      password: ${REDIS_PASSWORD}
#      database: 0
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 550000

mybatis-plus:
  mapper-locations: classpath*:./mappers/**/*.xml

server:
  port: 8083
  address: 0.0.0.0

resend:
  api-key: ${RESEND_API_KEY}
  from-email: ${RESEND_FROM_EMAIL}

wechat:
  appId: ${WECHAT_APP_ID}
  secret: ${WECHAT_SECRET}
  grantType: authorization_code
  loginUrl: https://api.weixin.qq.com/sns/jscode2session