#
#spring:
#  # 邮件配置
#  mail:
#    host: smtp.example.com
#    port: 587
#    username: your-email@example.com
#    password: your-email-password
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

spring:
  application:
    name: gh-weixin
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  datasource:
    url: jdbc:mysql://localhost:3306/gif_hub?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:./mappers/**/*.xml

# 端口
server:
  port: 8083


# 邮件配置
resend:
  api-key: ''
  from-email: 'noreply@mynnmy.top'

# 微信配置
wechat:
  appId: ''
  secret: ''
  grantType: 'authorization_code'
  loginUrl: 'https://api.weixin.qq.com/sns/jscode2session'
